services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: outrider-net-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: outridernet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass@123
      TZ: UTC
      PGTZ: UTC

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgis/data

volumes:
  postgres_data: